# Generated by Django 3.0.8 on 2021-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='topic',
            field=models.DateField(blank=True, help_text='العنوان', null=True),
        ),
    ]
