# Generated by Django 3.0.8 on 2021-09-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210827_0013'),
        ('teacher', '0002_auto_20210901_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_zoom', to='courses.Episode'),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='join_url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='topic',
            field=models.DateField(blank=True, help_text='عنوان الجلسة', null=True),
        ),
    ]
