# Generated by Django 3.0.8 on 2021-09-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210827_0013'),
        ('teacher', '0003_auto_20210901_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_zoom', to='courses.Episode'),
        ),
    ]
