# Generated by Django 3.0.8 on 2021-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210901_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='join_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='topic',
            field=models.CharField(blank=True, help_text='عنوان الجلسة', max_length=300, null=True),
        ),
    ]
