# Generated by Django 3.0.8 on 2021-08-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_subject_nameid'),
        ('student', '0003_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(blank=True, null=True, verbose_name='Reading')),
                ('review', models.FloatField(blank=True, null=True, verbose_name='Review')),
                ('memorizing', models.FloatField(blank=True, null=True, verbose_name='Memorizing')),
                ('num_of_pages', models.CharField(blank=True, max_length=22, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Episode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'unique_together': {('episode', 'student')},
            },
        ),
    ]
