# Generated by Django 3.0.8 on 2021-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210823_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='nameid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
