# Generated by Django 3.0.8 on 2021-08-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_nameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseNo', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
