# Generated by Django 3.0.8 on 2021-08-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_nameid'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='num_of_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject4',
        ),
        migrations.AddField(
            model_name='score',
            name='memorizing',
            field=models.FloatField(blank=True, null=True, verbose_name='Memorizing'),
        ),
        migrations.AddField(
            model_name='score',
            name='num_of_pages',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='reading',
            field=models.FloatField(blank=True, null=True, verbose_name='Reading'),
        ),
        migrations.AddField(
            model_name='score',
            name='review',
            field=models.FloatField(blank=True, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='courses.Episode'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='courses.Course'),
        ),
    ]
