# Generated by Django 3.0.8 on 2021-08-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210826_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
