# Generated by Django 3.0.8 on 2021-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
