# Generated by Django 3.0.8 on 2021-08-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210827_0013'),
        ('student', '0004_attendance_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('episode', 'student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
